name = "icoky"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[vars]
BOT_TOKEN = "8716545255:AAEevulA_Q8sz-cjEXs_9-mN8leuoGI-RSk"
CLOUDINARY_CLOUD_NAME = "dneusgyzc"
